import type { NextPage } from "next";
import Head from "next/head";
import { Layout, Menu, Breadcrumb, Button } from "antd";
import styles from "../styles/Home.module.css";

const { Header, Content, Footer } = Layout;

const Home: NextPage = () => {
  return (
    <Layout className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className={styles.logo} />
        <Menu theme="dark" mode="horizontal" defaultSelectedKeys={["find"]}>
          <Menu.Item key={"find"}>Find a slot</Menu.Item>
          <Menu.Item key={"my-slots"}>My slots</Menu.Item>
          <Menu.Item key={"login"} className={styles.login}>
            Login
          </Menu.Item>
        </Menu>
      </Header>
      <Content className={styles.content}>
        <Breadcrumb style={{ margin: "16px 0" }}>
          <Breadcrumb.Item>Home</Breadcrumb.Item>
          <Breadcrumb.Item>List</Breadcrumb.Item>
          <Breadcrumb.Item>App</Breadcrumb.Item>
        </Breadcrumb>
        <div className="site-layout-content">
          Content<Button type="primary">Button</Button>
        </div>
      </Content>
      <Footer style={{ textAlign: "center" }}>
        Ant Design ©2018 Created by Ant UED
      </Footer>
    </Layout>
  );
};

export default Home;
